without cheri ccall attribute for sandbox_invoke: seal violation error.
USER_CHERI_EXCEPTION: pid 759 tid 100047 (hello.exe), uid 0: CP2 fault (type 0x32)
Process arguments: ./hello.exe
Trapframe Register Dump:
$0: 0                  at: 0x48010            v0: 0x401d0            v1: 0
a0: 0x1                a1: 0x4004d000         a2: 0x15               a3: 0
a4: 0                  a5: 0                  a6: 0x1000             a7: 0
t0: 0x2                t1: 0x400e48b0         t2: 0x2                t3: 0x402b7810
s0: 0x7ffffefaf8       s1: 0x1                s2: 0x7ffffefae8       s3: 0
s4: 0                  s5: 0                  s6: 0                  s7: 0
t8: 0x1                t9: 0x15               k0: 0                  k1: 0
gp: 0x48010            sp: 0x7ffffef9e0       s8: 0x7ffffef9e0       ra: 0x20b04
status: 0x408084b3 mullo: 0; mulhi: 0; badvaddr: 0x4d49fb4b
cause: 0x48; pc: 0x20448
BadInstr: 0x48a11001 ccall      c1,c2
CHERI cause: ExcCode: 0x03 RegNum: $c01 (seal violation)
$ddc: v:1 s:0 p:0007817d b:0000000000000000 l:0000008000000000 o:0 t:-1
$c01: v:1 s:0 p:0007817d b:0000000000010884 l:0000000000000015 o:15 t:-1
$c02: v:1 s:0 p:0007817d b:000000004004d000 l:0000000000000015 o:15 t:-1
$c03: v:1 s:1 p:00068117 b:0000000000000000 l:0000008000000000 o:20450 t:0
$c04: v:1 s:1 p:0007817d b:0000000000000000 l:0000008000000000 o:0 t:0
$c05: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c06: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c07: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c08: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c09: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c10: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c11: v:1 s:0 p:0007817d b:0000000000000000 l:0000008000000000 o:0 t:-1
$c12: v:1 s:0 p:00068117 b:0000000000000000 l:0000008000000000 o:40050000 t:-1
$c13: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c14: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c15: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c16: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c17: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c18: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c19: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c20: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c21: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c22: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c23: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c24: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c25: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c26: v:1 s:0 p:0007817d b:0000000000000000 l:0000008000000000 o:0 t:-1
$c27: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c28: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c29: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c30: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c31: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$pcc: v:1 s:0 p:00068117 b:0000000000000000 l:0000008000000000 o:20448 t:-1
pid 759 (hello.exe), jid 0, uid 0: exited on signal 34 (core dumped)
root@qemu-cheri128-root:~ #

root@qemu-cheri128-root:~ # ./hello.exe
hello world
cheritest setup
begin.
         seal cap created as:
tag 1 s 0 perms 00000281 type ffffffffffffffff
        base 0000000000000000 length 0000000000800000
         code cap created as:
tag 1 s 0 perms 00068117 type ffffffffffffffff
        base 0000000000000000 length 0000008000000000
         code cap sealed as:
tag 1 s 1 perms 00068117 type 0000000000000000
        base 0000000000000000 length 0000008000000000
        creating hybrid data cap (DDC)...
         data cap created as:
tag 1 s 0 perms 0007817d type ffffffffffffffff
        base 0000000000000000 length 0000008000000000
         data cap sealed as:
tag 1 s 1 perms 0007817d type 0000000000000000
        base 0000000000000000 length 0000008000000000
done.
the default DDC is:
tag 1 s 0 perms 0007817d type ffffffffffffffff
        base 0000000000000000 length 0000008000000000

the default PCC is:
tag 1 s 0 perms 00068117 type ffffffffffffffff
        base 0000000000000000 length 0000008000000000

the default IDC is:
tag 1 s 0 perms 0007817d type ffffffffffffffff
        base 0000000000000000 length 0000008000000000
now start testing...
Signal 34 (core dumped)
root@qemu-cheri128-root:~ #