ddc: sealing error:
USER_CHERI_EXCEPTION: pid 616 tid 100056 (hello.exe), uid 0: CP2 fault (type 0x32)
Process arguments: ./hello.exe
Trapframe Register Dump:
$0: 0                  at: 0x8107             v0: 0x1                v1: 0x1
a0: 0x6                a1: 0x30               a2: 0                  a3: 0
a4: 0                  a5: 0                  a6: 0                  a7: 0
t0: 0x25               t1: 0xc                t2: 0x6e               t3: 0
s0: 0x1                s1: 0                  s2: 0                  s3: 0
s4: 0                  s5: 0                  s6: 0                  s7: 0
t8: 0x10               t9: 0x1484             k0: 0                  k1: 0
gp: 0                  sp: 0xffffffffffffffc0 s8: 0                  ra: 0
status: 0x408084b3 mullo: 0x75bb09; mulhi: 0x10; badvaddr: 0x1640c2d0
cause: 0x48; pc: 0x10de8
BadInstr: 0x4802110b cseal      c2,c2,c4
CHERI cause: ExcCode: 0x02 RegNum: $c02 (tag violation)
$ddc: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c01: v:1 s:0 p:0007817d b:0000000000152060 l:0000000000000010 o:0 t:-1
$c02: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c03: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000030600 o:30040 t:-1
$c04: v:1 s:0 p:00000081 b:0000000000000002 l:0000000000000001 o:0 t:-1
$c05: v:1 s:0 p:0007817d b:0000007ffffcfb20 l:0000000000000010 o:0 t:-1
$c06: v:1 s:0 p:0007817d b:0000007ffffcf0d0 l:0000000000000010 o:0 t:-1
$c07: v:1 s:0 p:0007817d b:0000007ffffcf038 l:0000000000000001 o:0 t:-1
$c08: v:1 s:0 p:0007817d b:0000007ffffcf038 l:0000000000000001 o:0 t:-1
$c09: v:1 s:0 p:0007817d b:0000007ffffcf018 l:0000000000000001 o:0 t:-1
$c10: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c11: v:1 s:0 p:0007817d b:0000007ffbff0000 l:0000000003fe0000 o:3fdfb60 t:-1
$c12: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000030600 o:110e0 t:-1
$c13: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c14: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c15: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c16: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c17: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000030600 o:10dc8 t:-1
$c18: v:1 s:0 p:0007817d b:0000007ffffef7c0 l:0000000000000020 o:0 t:-1
$c19: v:1 s:0 p:0007817d b:0000007ffffef7e0 l:0000000000000170 o:0 t:-1
$c20: v:1 s:0 p:00068117 b:0000000000000000 l:0000000000556000 o:150040 t:-1
$c21: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c22: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c23: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c24: v:1 s:0 p:0007817d b:0000007ffbff0000 l:0000000003fe0000 o:3fdfb60 t:-1
$c25: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c26: v:1 s:0 p:00078117 b:000000004015c000 l:000000000025b000 o:245a20 t:-1
$c27: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c28: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c29: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c30: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$c31: v:0 s:0 p:00000000 b:0000000000000000 l:ffffffffffffffff o:0 t:-1
$pcc: v:1 s:0 p:00068117 b:0000000000120000 l:0000000000030600 o:10de8 t:-1
pid 616 (hello.exe), jid 0, uid 0: exited on signal 34 (core dumped)